name: End-to-end tests
on: [push]
jobs:
    cypress-run:
        runs-on: macos-latest
        steps:
            - name: Checkout
            uses: actions/checkout@v3
            #install NPM dependencies
            #and run all cypress tests
            - name: Cypress run
            uses: cypress-io/github-action@v5